apiVersion: v1
kind: Service
metadata:
  name: cadvisor
  namespace: monitoring
  labels:
    app: cadvisor
spec:
  selector:
    app: cadvisor
  ports:
    - protocol: TCP
      port: 8080       # Service port
      targetPort: 8080 # Pod port