{
 "title": "Per Pod Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "per pod cpu usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(pod) (\n  rate(container_cpu_usage_seconds_total{namespace=\"default\", container!=\"\", pod!=\"\"}[5m])\n)\n/\nsum by(pod) (\n  kube_pod_container_resource_limits{namespace=\"default\", resource=\"cpu\"}\n)\n*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "per pod memory usage %",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(pod) (\n  container_memory_working_set_bytes{namespace=\"default\", container!=\"\", pod!=\"\"}\n)\n/\nsum by(pod) (\n  kube_pod_container_resource_limits{namespace=\"default\", resource=\"memory\"}\n)\n* 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network throughput per node - TX (Mbps)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (pod) (\n  rate(container_network_transmit_bytes_total{namespace=\"default\"}[5m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "pod phase",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "kube_pod_status_phase{namespace=\"default\", pod!=\"\" , phase=\"Running\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network throughput per node - RX (Mbps)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by (pod) (\n  rate(container_network_receive_bytes_total{namespace=\"default\"}[5m])\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}