---
- hosts: loadgenerator-vm
  gather_facts: false
  
  vars:
    image_tar: "{{ lookup('env', 'LOADGENERATOR_IMAGE_PATH') }}"
    image_name: loadgenerator:latest
    container_name: loadgenerator
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    local_results_dir: "{{ playbook_dir }}/results/{{ lookup('env', 'CLIENTS') }}"
    

  tasks:
    - name: Show environment variables
      debug:
        msg:
          FRONTEND_ADDR: "{{ lookup('env', 'FRONTEND_ADDR') }}"
          USERS: "{{ lookup('env', 'USERS') }}"
          RATE: "{{ lookup('env', 'RATE') }}"
          RUN_TIME: "{{ lookup('env', 'RUN_TIME') }}"
          IMAGE_TAR: "{{ lookup('env', 'LOADGENERATOR_IMAGE_PATH') }}"    

    - name: Wait for connection (600s default)
      wait_for_connection:                   

    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start and enable Docker
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Copy Docker image tar to VM
      copy:
        src: "{{ image_tar }}"
        dest: /tmp/{{ image_tar }}

    - name: Load Docker image from tar
      command: docker load -i /tmp/{{ image_tar }}

    - name: Run loadgenerator container
      docker_container:
        name: "{{ container_name }}"
        image: "{{ image_name }}"
        state: started
        restart_policy: no      
        detach: no
        env: 
          FRONTEND_ADDR: "{{ lookup('env', 'FRONTEND_ADDR') }}"
          USERS: "{{ lookup('env', 'USERS') }}"
          RATE: "{{ lookup('env', 'RATE') }}"
          RUN_TIME: "{{ lookup('env', 'RUN_TIME') }}"
        volumes:
        - /tmp/locust:/locust/csv        

    - name: Ensure rsync is installed on remote host
      apt:
        name: rsync
        state: present
      become: yes

    - name: Ensure local results directory for each host exists
      delegate_to: localhost
      become: false 
      file:
        path: "{{ local_results_dir }}/{{ inventory_hostname }}/"
        state: directory
        mode: '0777'  
       
    - name: Copy file and set permissions with Ansible
      synchronize:
              src: /tmp/locust/
              dest: "{{ local_results_dir }}/{{ inventory_hostname }}"
              mode: pull



